### ISSUE TITLE
Verhalten von moment.js

### ISSUE THREAD

**Issue by Steph0r** [Steph0r/timesheet#13]
Vielleicht liegt es daran, dass ich etwas krank bin, aber irgendwie verstehe ich das Verhalten von Moment.js an einer Stelle nicht.

Auf dem Screenshot sieht man die Woche vom 04.03 bis zum 10.03, aber im LocalStorage werden nicht wie ich dachte genau diese tage mit jeweils 00:00 Uhr gespeichert, sondern der 03.03 bis zum 09.03 um 23:00 Uhr.

![screenshot 2019-03-03 19 34 31](https://user-images.githubusercontent.com/3080889/53699782-33ac0b00-3dec-11e9-842f-bb60e5edfa41.png)

Auf der Konsole passiert das selbe: `startOf('day')` ist nicht heute 00:00, sondern gestern um 23:00.

![momentbehavior](https://user-images.githubusercontent.com/3080889/53699807-7968d380-3dec-11e9-8b81-6c3d06a9646a.PNG)

 Verstehe ich hier die Funktion von Moment.js falsch? Oder verwenden wir es falsch? Oder haben wir ein Zeitzonen/Sommerzeit-Problem?

**Comment by thomasbreitbach** [comment]
Ich glaube es ist so. Wir haben in der index.html die /locale/de.js eingebunden. Dadurch liefert die toString() einen String im entsprechenden Format:

    moment().toString()
    "Sun Mar 03 2019 20:25:43 GMT+0100"

Das interne Datum ist aber eigentlich weiterhin in die [Zulu-Zeit/UTC](https://de.wikipedia.org/wiki/Koordinierte_Weltzeit):

    moment()
    Object { _isAMomentObject: true, _isUTC: false, _pf: {…}, _locale: {…}, _d: Date 2019-03-03T19:25:55.675Z, _isValid: true }

toJSON() und JSON.stringify() liefern beide die "interne" Zulu-Zeit:

    moment().toJSON()
    "2019-03-03T19:44:08.439Z"

    JSON.stringify(moment())
     "\"2019-03-03T19:44:38.668Z\""

D.h. 00:00 Uhr Mitternacht wird dann zu 23:00 Uhr am Vortag. Beim parsen der Zulu-Zeit aus dem LocalStorage wird dann wieder in 'de'-Locale umgewandelt und die für uns richtige Zeit bzw das korrekte Datum angezeigt.
